---
title: "TCM_vis"
author: "Lucy Williams"
date: "`r Sys.Date()`"
output: html_document
---

## Libraries

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Load necessary libraries
library(tidyverse)
library(ggpubr)
library(patchwork) 
library(hrbrthemes) 
library(ggthemes)

#Set a custom theme for ggplot
theme_set(theme_tufte())
theme_update(plot.title =element_text(hjust=0.5),
             axis.line.x = element_line(color="black", size=1), 
             element_line(color="black", size=1),
             text = element_text(size=20),
             axis.text = element_text(size=15)) 
```

## Data import - Current

```{r}
#Load data from TCM_enviro folder 

first_deployment <- read_csv("TCM_tidy/06092023_Avg_Current.csv")
second_deployment <- read_csv("TCM_tidy/07272023_Avg_Current.csv")
third_deployment <- read_csv("TCM_tidy/08292023_Avg_Current.csv")
fourth_deployment <- read_csv("TCM_tidy/09112023_Avg_Current.csv")
```

## Combine dataframes into one - Current

```{r}
TCM_all <- rbind(first_deployment, second_deployment, third_deployment, fourth_deployment)
```

## Plot - Current

```{r}
ggplot(TCM_all, aes(x = Date)) +
  geom_line(aes(y = avg_speed), color = "blue") +
  geom_line(aes(y = max_speed), color = "black") +
  geom_line(aes(y = min_speed), color = "black") +
  ylab("Speed (cm/s)") + xlab("")

ggplot(TCM_all, aes(x = Date)) +
  geom_line(aes(y = avg_nvelocity), color = "red") +
  geom_line(aes(y = avg_evelocity), color = "blue") +
  ylab("Speed (cm/s)") + xlab("")
```

## Data download - Temperature

```{r}
first_temp <- read_csv("TCM_tidy/06092023_Temp.csv")
second_temp <- read_csv("TCM_tidy/07272023_Temp.csv")
third_temp <- read_csv("TCM_tidy/08292023_Temp.csv")
fourth_temp <- read_csv("TCM_tidy/09112023_Temp.csv")
```

## Combine data frames into one - Temperature

```{r}
Temp_all <- rbind(first_temp, second_temp, third_temp,fourth_temp)
```

## Plot - Temperature

```{r}
ggplot(Temp_all, aes(x = `ISO 8601 Time`, y = `Temperature (C)`)) +
  geom_line(shape =1) + geom_smooth() + xlab("")
```
